'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createHmac}=require('node:crypto');
const A=require('../src/adaptive.js');
const env={AI_MODE:'live',TEXT_PROVIDER:'vercel',AI_GATEWAY_API_KEY:'fixture-only',OPENAI_MODEL:'gpt-5.6-luna',ALLOWED_ORIGIN:'https://fixture.example',APP_SESSION_SECRET:'fixture-session-secret-012345678901234567890123'};
const input=(patch={})=>({runId:'adaptive-run',sequence:1,mode:'expedition',stage:0,wave:0,completion:'wave',difficulty:'standard',autoplay:false,currentLevel:0,telemetry:{kills:8,parries:2,grazes:1,damageTaken:1,seconds:12.25,hpRatio:.9},...patch});
function req(body,headers={}){const sid='adaptive-session',exp=Math.floor(Date.now()/1000)+900;const csrf=createHmac('sha256',env.APP_SESSION_SECRET).update(`csrf:${sid}:${exp}`).digest('base64url');return new Request('https://fixture.example/api/adaptive',{method:'POST',headers:{'Content-Type':'application/json',origin:env.ALLOWED_ORIGIN,cookie:`nemesis_app_session=${createSessionToken({secret:env.APP_SESSION_SECRET,sid,exp})}`,'x-nemesis-csrf':csrf,...headers},body:JSON.stringify(body)});}
const {createSessionToken}=require('../server/access.mjs');
function fixtures({deny=false}={}){const states=new Map(),calls=[];return {calls,store:{eval:async(script,keys,args)=>{const k=keys[0],s=states.get(k)||{sequence:-1};if(script.includes('pending=true')){const n=Number(args[0]),digest=args[1];if(n<=s.sequence)return [0,n===s.sequence&&s.digest===digest?'duplicate':'stale',JSON.stringify(s)];states.set(k,{sequence:n,digest,pending:true});return [1,'started',''];}const n=Number(args[0]),digest=args[1],result=JSON.parse(args[2]);if(s.sequence!==n||s.digest!==digest||!s.pending)return [0,'stale'];s.pending=false;s.result=result;states.set(k,s);return [1,'saved'];}},quota:{reserve:async x=>{calls.push(['reserve',x]);return deny?{ok:false}:{ok:true,reservationId:'adaptive-res'};},markStarted:async()=>{calls.push(['start']);return {ok:true};},settle:async x=>{calls.push(['settle',x]);return {ok:true};}}};}
const decision={skill:'steady',adjustment:'hold',line:'Keep reading the pattern.',rationale:'Aggregate telemetry is mixed; hold at the current authored level.'};
function upstream(payload=decision,usage={input_tokens:100,output_tokens:80}){return Response.json({status:'completed',usage,output:[{content:[{type:'output_text',text:JSON.stringify(payload)}]}]});}
test('adaptive rejects unauthenticated and malformed requests before spending',async()=>{const {handle}=await import('../server/adaptive.mjs');const f=fixtures();assert.ok((await handle(req({request:input()},{origin:'https://wrong.example'}),{env,...f,fetcher:()=>{throw Error('called')}})).status>=400);assert.equal((await handle(req({request:input({sequence:2})}),{env,...f,fetcher:()=>{throw Error('called')}})).status,400);assert.equal(f.calls.length,0);});
test('adaptive calls exact Luna model and returns validated metadata',async()=>{const {handle}=await import('../server/adaptive.mjs');const f=fixtures();let payload;const r=await handle(req({request:input()}),{env,...f,fetcher:async(_u,o)=>{payload=JSON.parse(o.body);return upstream();}});const out=await r.json();assert.equal(r.status,200);assert.equal(payload.model,'openai/gpt-5.6-luna');assert.equal(out.provider,'openai');assert.equal(out.runId,'adaptive-run');assert.equal(out.sequence,1);});
test('budget denial does not call upstream',async()=>{const {handle}=await import('../server/adaptive.mjs');const f=fixtures({deny:true});let called=false;const r=await handle(req({request:input({runId:'budget-run'})}),{env,...f,fetcher:()=>{called=true;}});assert.equal(r.status,429);assert.equal(called,false);});
test('same sequence with changed telemetry is rejected by digest dedupe',async()=>{const {handle}=await import('../server/adaptive.mjs');const f=fixtures();const fetcher=async()=>upstream();assert.equal((await handle(req({request:input({runId:'dedupe-run'})}),{env,...f,fetcher})).status,200);const r=await handle(req({request:input({runId:'dedupe-run',telemetry:{...input().telemetry,kills:99}})}),{env,...f,fetcher});assert.equal(r.status,409);});
test('invalid model output falls back to local hold and settles reservation',async()=>{const {handle}=await import('../server/adaptive.mjs');const f=fixtures();const r=await handle(req({request:input({runId:'invalid-run'})}),{env,...f,fetcher:async()=>upstream({...decision,adjustment:'hack'})});const out=await r.json();assert.equal(r.status,200);assert.equal(out.provider,'local-rules');assert.equal(out.decision.adjustment,'hold');assert.ok(f.calls.some(x=>x[0]==='settle'));});
test('missing usage retains conservative reservation cost',async()=>{const {handle}=await import('../server/adaptive.mjs');const f=fixtures();const out=await (await handle(req({request:input({runId:'usage-run'})}),{env,...f,fetcher:async()=>upstream(decision,null)})).json();assert.equal(out.accountedMicrodollars,10000);assert.equal(f.calls.at(-1)[1].actualMicrodollars,10000);});

test('identical retry returns cached analysis without another reservation',async()=>{const {handle}=await import('../server/adaptive.mjs');const f=fixtures();let calls=0;const options={env,...f,fetcher:async()=>{calls++;return upstream();}};const first=await(await handle(req({request:input()}),options)).json();const retry=await(await handle(req({request:input()}),options)).json();assert.equal(retry.deduplicated,true);assert.deepEqual(retry.decision,first.decision);assert.equal(calls,1);assert.equal(f.calls.filter(x=>x[0]==='reserve').length,1);});
test('older in-flight analysis cannot finish after the next encounter and still accounts for usage',async()=>{const {handle}=await import('../server/adaptive.mjs');const f=fixtures();let release,ready;const started=new Promise(r=>ready=r);const old=handle(req({request:input()}),{env,...f,fetcher:async()=>{ready();return new Promise(r=>release=r);}});await started;const newer=await handle(req({request:input({sequence:2,wave:1})}),{env,...f,fetcher:async()=>upstream()});assert.equal(newer.status,200);release(upstream());assert.equal((await old).status,409);assert.equal(f.calls.filter(x=>x[0]==='settle').length,2);});
