'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/campaign.js');
const I=require('../src/intelligence.js');
const {createHmac}=require('node:crypto');
const {createSessionToken}=require('../server/access.mjs');
const env={AI_MODE:'live',TEXT_PROVIDER:'vercel',AI_GATEWAY_API_KEY:'fixture-only-key',OPENAI_MODEL:'gpt-5.6-luna',ALLOWED_ORIGIN:'https://fixture.example',APP_SESSION_SECRET:'fixture-session-secret-012345678901234567890123'};
const req=(body,headers={})=>new Request('http://localhost/api/campaign',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});
function authReq(body,extra={}){const sid='campaign-session',exp=Math.floor(Date.now()/1000)+900,csrf=createHmac('sha256',env.APP_SESSION_SECRET).update(`csrf:${sid}:${exp}`).digest('base64url');return req(body,{origin:env.ALLOWED_ORIGIN,cookie:`nemesis_app_session=${createSessionToken({secret:env.APP_SESSION_SECRET,sid,exp})}`,'x-nemesis-csrf':csrf,...extra});}
function fixtures(){const calls=[],actions=[],states=new Map();return {calls,actions,store:{eval:async(_lua,keys,args)=>{const a=JSON.parse(args[0]);actions.push(a);assert.match(keys[0],/^nemesis:campaign:/);let s=states.get(keys[0])||{revision:0,intent:-1};if(a.op==='begin'){if(a.revision!==s.revision||a.intent<=s.intent)return [0,'stale'];s={...s,intent:a.intent,requestId:a.requestId,proposal:null};}else if(a.op==='invalidate'){if(a.intent>s.intent)s={...s,intent:a.intent,proposal:null,requestId:null};}else if(a.op==='finish'){if(a.intent!==s.intent||a.requestId!==s.requestId||s.proposal)return [0,'stale'];s.proposal=a.proposal;}else if(a.op==='sign'){if(a.revision!==s.revision||a.intent!==s.intent||!s.proposal||a.proposalId!==s.proposal.proposalId||a.digest!==s.proposal.digest)return [0,'stale'];s={...s,revision:s.revision+1,signed:s.proposal,proposal:null};}states.set(keys[0],s);return [1,JSON.stringify(s)];}},quota:{reserve:async a=>{calls.push(['reserve',a]);return {ok:true,reservationId:'campaign-res'};},markStarted:async()=>{calls.push(['started']);return {ok:true};},settle:async a=>{calls.push(['settle',a]);return {ok:true};}}};}
function campaignBody(context={mode:'expedition',stage:1}){const allowed=C.offers(context).map(x=>x.id);return {action:'propose',request:{task:'negotiate',prompt:'sanctuary',seed:'campaign-test',stage:context.stage,allowed,telemetry:{kills:2}},runId:'campaign-run',requestId:'campaign-req',intentVersion:2,context};}
function upstream(body,mutate=x=>x){const d=mutate(I.mock(body.request));return Response.json({status:'completed',usage:{input_tokens:100,output_tokens:100},output:[{content:[{type:'output_text',text:JSON.stringify(d)}]}]});}
test('campaign catalog follows authored offers and rejects unavailable classic stages',()=>{for(const mode of ['expedition','gauntlet'])for(let stage=0;stage<6;stage++)assert.equal(C.offers({mode,stage}).length,3);assert.throws(()=>C.context({mode:'classic',stage:3}));});
test('clean request requires exact stage offer list and negotiate task',()=>{const context={mode:'expedition',stage:1},allowed=C.offers(context).map(x=>x.id),base={task:'negotiate',prompt:'safe',seed:'campaign-test',stage:1,allowed,telemetry:{kills:0}};assert.equal(C.cleanRequest(base,context).allowed.join(','),allowed.join(','));assert.throws(()=>C.cleanRequest({...base,task:'director'},context));assert.throws(()=>C.cleanRequest({...base,allowed:[...allowed].reverse()},context));});
test('offline campaign propose returns canonical unsigned commentary without model prose',async()=>{const context={mode:'expedition',stage:0},allowed=C.offers(context).map(x=>x.id),body={action:'propose',request:{task:'negotiate',prompt:'slow bullets',seed:'campaign-test',stage:0,allowed,telemetry:{kills:0}},runId:'campaign_run_1',requestId:'campaign_req_1',intentVersion:0,context};const {handle}=await import('../server/campaign.mjs');const response=await handle(req(body),{env:{AI_MODE:'local'}});assert.equal(response.status,200);const result=await response.json();assert.equal(result.campaignPact.id,'mercy');const commentary=JSON.parse(result.commentary);assert.equal(commentary.status,'unsigned');assert.equal(commentary.campaignPact.gift,result.campaignPact.gift);assert.equal(commentary.instruction,'Review the canonical offer and click Sign to apply it.');});
test('campaign namespace is isolated and rejects unknown namespace',async()=>{const {proposalStore}=await import('../server/proposals.mjs');const store={eval:async()=>[1,JSON.stringify({revision:0,intent:0})]};assert.doesNotThrow(()=>proposalStore(store,'session_123','campaign'));assert.throws(()=>proposalStore(store,'session_123','unknown'),/INVALID_NAMESPACE/);});
test('paid campaign rejects origin, session and csrf before upstream or quota',async()=>{const {handle}=await import('../server/campaign.mjs');let n=0;for(const headers of [{origin:'https://wrong.example'},{cookie:''},{'x-nemesis-csrf':'wrong'}]){const f=fixtures();assert.ok((await handle(authReq(campaignBody(),headers),{env,...f,fetcher:()=>{n++;}})).status>=400);assert.equal(f.calls.length,0);}assert.equal(n,0);});
test('paid campaign sends canonical catalog, Luna schema/tier, and stores full decision',async()=>{const {handle}=await import('../server/campaign.mjs');const f=fixtures(),body=campaignBody();let payload;const response=await handle(authReq(body),{env,...f,fetcher:async(u,o)=>{payload=JSON.parse(o.body);return upstream(body,x=>({...x,directorId:'balanced'}));}}),v=await response.json();assert.equal(response.status,200);assert.equal(v.provider,'openai');assert.equal(v.decision.task,'negotiate');assert.equal(v.decision.directorId,'balanced');assert.equal(v.campaignPact.id,v.decision.contractId);assert.equal(payload.model,'openai/gpt-5.6-luna');assert.equal(payload.service_tier,'default');assert.equal(payload.text.format.strict,true);assert.match(payload.instructions,/Slow Violence|Sacred Ground/);assert.equal(f.actions.at(-1).op,'finish');assert.equal(f.actions.at(-1).proposal.spec.contractId,v.decision.contractId);assert.equal(v.accountedMicrodollars,145);});
test('campaign wrong digest and concurrent double sign are rejected atomically',async()=>{const {handle}=await import('../server/campaign.mjs'),f=fixtures(),body=campaignBody(),p=await(await handle(authReq(body),{env,...f,fetcher:async()=>upstream(body)})).json();const sign={action:'sign',runId:body.runId,intentVersion:body.intentVersion,revision:0,proposalId:p.proposalId,digest:p.digest};assert.equal((await handle(authReq({...sign,digest:'wrong'}),{env,...f})).status,409);const statuses=await Promise.all([handle(authReq(sign),{env,...f}),handle(authReq(sign),{env,...f})]);assert.deepEqual(statuses.map(x=>x.status).sort(),[200,409]);});
test('late response after cancellation cannot publish and remains accounted',async()=>{const {handle}=await import('../server/campaign.mjs'),f=fixtures(),body=campaignBody();let release,start;const ready=new Promise(r=>start=r);const pending=handle(authReq(body),{env,...f,fetcher:async()=>{start();return new Promise(r=>release=r);}});await ready;const cancel={action:'cancel',runId:body.runId,intentVersion:3};assert.equal((await handle(authReq(cancel),{env,...f})).status,200);release(upstream(body));assert.equal((await pending).status,409);assert.ok(f.calls.some(x=>x[0]==='settle'));});
test('kill switch and exhausted budget never call inference',async()=>{const {handle}=await import('../server/campaign.mjs');let n=0;const fetcher=()=>{n++;};const f=fixtures();assert.equal((await handle(authReq(campaignBody()),{env:{...env,OPENAI_KILL_SWITCH:'1'},...f,fetcher})).status,503);const exhausted=fixtures();exhausted.quota.reserve=async()=>({ok:false});assert.equal((await handle(authReq(campaignBody()),{env,...exhausted,fetcher})).status,429);assert.equal(n,0);});
test('invalid model output falls back and cache write accounting is conservative',async()=>{const {handle}=await import('../server/campaign.mjs');for(const mutate of [x=>({...x,directorId:'god-mode'}),x=>({...x,extra:'bad'})]){const f=fixtures(),body=campaignBody();const response=await handle(authReq(body),{env,...f,fetcher:async()=>Response.json({status:'completed',usage:{input_tokens:100,output_tokens:100,input_tokens_details:{cache_write_tokens:20}},output:[{content:[{type:'output_text',text:JSON.stringify(mutate(I.mock(body.request)))}]}]})});const v=await response.json();assert.equal(v.provider,'local-rules');assert.equal(v.accountedMicrodollars,141);}});
