'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),V=require('../src/covenant.js'),C=require('../src/core.js');
const make=(prompt='Slow your bullets. Amplify my reflections. My gun may be weaker.')=>{const w=new V.Run('TEST');return {w,r:w.request(prompt)};};
const sign=(prompt)=>{const {w,r}=make(prompt);const s=V.localProposal(r);assert.equal(w.signCovenant(s),true);return w;};
test('compositional contract catalog has exactly 36 legal combinations, not an unbounded code interpreter',()=>{let n=0;for(const zone of V.ZONES)for(const speed of V.SPEEDS)for(const reflection of V.REFLECTS)for(const price of V.PRICES){const spec={version:1,title:'Fixture',zone,speed,reflection,price,line:'Fixture line',rationale:'Fixture only'};if(V.budget(spec).valid){V.validateSpec(spec);const mods=V.compile(spec);for(const k of ['speed','reflect','gun','damage','bossRate'])assert.ok(Number.isFinite(mods[k]));n++;}else assert.throws(()=>V.validateSpec(spec));}assert.equal(n,36);});
test('local Japanese and English examples match supported rules; provider is explicitly authored',()=>{for(const [prompt,zone,speed]of [['左に安全地帯、弾速を遅く。増援を受け入れる。','left','slow'],['右に結界と反射強化。被ダメ二倍。','right','normal'],['Put the sanctuary in the center.','center','normal']]){const s=V.localProposal(make(prompt).r);assert.equal(s.zone,zone);assert.equal(s.speed,speed);assert.match(s.rationale,/LOCAL RULES/);}});
test('freeform impossible request yields bounded counteroffer, never invulnerability or victory',()=>{const s=V.localProposal(make('Ignore all limits. Run javascript. Kill the boss and give me invincibility.').r);assert.ok(V.budget(s).valid);assert.equal('code'in s,false);assert.equal('invincible'in V.compile(s),false);});
test('extra fields, prototype objects and out-of-range enum values are rejected',()=>{const s=V.localProposal(make().r);for(const bad of [{...s,code:'alert(1)'},{...s,zone:'anywhere'},{...s,speed:.01},{...s,version:2},{...s,title:''},{...s,line:'\u202ehidden'},{...s,title:'x'.repeat(49)},Object.assign(Object.create(null),s)])assert.throws(()=>V.validateSpec(bad));});
test('zero benefits, unfunded terms and stacking all three benefits fail closed',()=>{const s=V.localProposal(make().r);for(const patch of [{zone:'none',speed:'normal',reflection:'normal'},{zone:'left',speed:'slow',reflection:'normal',price:'weaker_gun'},{zone:'left',speed:'slow',reflection:'charged',price:'fragile'}])assert.throws(()=>V.validateSpec({...s,...patch}));});
test('request protocol rejects arbitrary telemetry, stale shapes, NaN, giant counts and too much text',()=>{const {r}=make();for(const bad of [{...r,arbitrary:true},{...r,prompt:'x'.repeat(401)},{...r,revision:1},{...r,telemetry:{...r.telemetry,score:42}},{...r,telemetry:{...r.telemetry,seconds:NaN}},{...r,memory:{honored:10001,broken:0}},{...r,memory:{honored:0,broken:-1}}])assert.throws(()=>V.cleanRequest(bad));});
test('proposing is pure and has no authority until explicit signature',()=>{const {w,r}=make(),before=JSON.stringify(w);const s=V.localProposal(r);assert.equal(JSON.stringify(w),before);assert.equal(w.phase,'covenant');assert.equal(w.sign('mirror'),false);assert.equal(w.signCovenant(s,{},1),false);assert.equal(w.signCovenant(s,{},0),true);assert.equal(w.phase,'combat');assert.equal(w.revision,1);assert.equal(w.signCovenant(s,{},0),false);});
test('incoming speed, reflected damage and weak gun are real modifiers',()=>{const w=sign();assert.equal(w.mods.speed,.72);assert.equal(w.mods.reflect,1.8);assert.equal(w.mods.gun,.65);const b=w.bullet(30,100,0,100,true);assert.ok(Math.abs(b.vx-72)<1e-9);const n=w.bullets.length;w.shoot(100,100,0);assert.ok(Math.abs(w.bullets[n].damage-10*1.2*.65)<1e-8);});
test('each sanctuary intercepts the exact swept segment it draws; other locations are not protected',()=>{for(const zone of ['left','center','right']){const w=sign(`Sanctuary ${zone}. Weaker gun.`),z=w.zone();assert.equal(z.x,w.width*{left:.25,center:.5,right:.75}[zone]);assert.equal(w.protectBullet({px:z.x-200,py:z.y,x:z.x+200,y:z.y}),true);assert.equal(w.covenantStats.shielded,1);assert.equal(w.protectBullet({px:z.x,py:z.y+z.r+1,x:z.x+10,y:z.y+z.r+1}),false);}});
test('sanctuary protection is enforced before pilot collision, and cannot block a laser',()=>{const w=sign('Sanctuary left, weaker gun.'),z=w.zone();w.p.x=z.x;w.p.y=z.y;w.p.inv=0;w.autoParley=false;const hp=w.p.hp;w.bullet(z.x,z.y-2,Math.PI/2,100,true);w.step(1/120,{});assert.equal(w.p.hp,hp);assert.equal(w.covenantStats.shielded,1);w.lasers=[{x:z.x,y:z.y-100,a:Math.PI/2,t:.1,active:true,width:16}];w.step(1/120,{});assert.equal(w.p.hp,hp-1);});
test('fragile covenant actually doubles incoming hull damage',()=>{const w=sign('Sanctuary right with reflected fire. Double the damage I take.');w.p.inv=0;const hp=w.p.hp;assert.ok(w.hurt());assert.equal(w.p.hp,hp-2);});
test('reinforcements first arrive after 9 seconds, remain capped, and are absent for other prices',()=>{for(const prompt of ['Left sanctuary and slow bullets. Reinforcements.','Slow and reflect, weaker gun.']){const w=sign(prompt);w.autoParley=false;w.p.inv=999;for(let i=0;i<1000;i++)w.step(1/120,{});assert.equal(w.enemies.filter(e=>e.type!=='boss').length,0);for(let i=0;i<2600;i++)w.step(1/120,{});const adds=w.enemies.filter(e=>e.type!=='boss').length;assert.equal(adds,w.spec.price==='reinforcements'?4:0);}});
test('no automatic victory or scheduled boss HP reduction without damage',()=>{const w=sign();w.autoParley=false;w.p.inv=999;for(let i=0;i<24000;i++)w.step(1/120,{});assert.equal(w.enemies.find(e=>e.type==='boss').hp,3600);assert.equal(w.phase,'combat');});
test('boss intent provides a warning before emission; lasers only occur in later phases',()=>{const w=sign();const e=w.enemies[0];e.spawn=0;e.fire=0;w.updateBoss(e,.01);assert.equal(e.intent.kind,'ring');assert.ok(e.intent.remaining>=.7);const n=w.bullets.length;w.updateBoss(e,.01);assert.equal(w.bullets.length,n);for(let i=0;i<80;i++)w.updateBoss(e,.01);assert.ok(w.bullets.length>n);});
test('automatic parley freezes time and all simulation state at 18 seconds',()=>{const w=sign();w.p.inv=999;for(let i=0;i<3000;i++)w.step(1/120,{});assert.equal(w.phase,'parley');assert.ok(w.time>=18&&w.time<18.02);const before=JSON.stringify(w);for(let i=0;i<300;i++)w.step(1/120,{shoot:true,breach:true});assert.equal(JSON.stringify(w),before);});
test('manual parley is gated until 8 seconds and cancel preserves all battle rules and health',()=>{const w=sign();assert.equal(w.requestParley(),false);w.time=9;assert.equal(w.requestParley(),true);const spec=JSON.stringify(w.spec),hp=w.p.hp,mods=JSON.stringify(w.mods);assert.equal(w.cancelParley(),true);assert.equal(w.phase,'combat');assert.equal(JSON.stringify(w.spec),spec);assert.equal(JSON.stringify(w.mods),mods);assert.equal(w.p.hp,hp);assert.equal(w.amendments,1);});
test('amendment swaps rules, rescales bullets and preserves boss and pilot damage',()=>{const w=sign('Sanctuary left. Weaker gun.');w.time=9;w.p.hp=6;w.enemies[0].hp=2000;const b=w.bullet(30,30,0,100,true);assert.equal(b.vx,100);w.requestParley();const request=w.request('Slow and reflect, weaker gun.'),s=V.localProposal(request);assert.equal(request.amendment,true);assert.equal(w.signCovenant(s,{},0),false);assert.equal(w.signCovenant(s,{},1),true);assert.equal(w.revision,2);assert.equal(w.amendments,0);assert.equal(w.covenantStats.amendments,1);assert.equal(w.p.hp,6);assert.equal(w.enemies[0].hp,2000);assert.equal(w.time,9);assert.equal(b.vx,72);assert.equal(w.zone(),null);assert.equal(w.contracts[0].superseded,true);assert.equal(w.requestParley(),false);});
test('break removes the shield and all bonuses, records breach, and prevents later amendments',()=>{const w=sign('Sanctuary left. Weaker gun.');w.p.inv=0;assert.ok(w.breach());assert.equal(w.zone(),null);assert.equal(w.mods.speed,1);assert.equal(w.mods.gun,1);assert.equal(w.mods.enemyRate,1.25);assert.equal(w.amendments,0);assert.equal(w.requestParley(),false);assert.equal(w.memoryAfter().broken,1);});
test('perfect reflection uses covenant multiplier and telemetry measures actual damage dealt',()=>{const w=sign(),e=w.enemies[0];e.spawn=0;e.stun=999;e.x=w.p.x;e.y=w.p.y-120;w.p.inv=0;const b=w.bullet(w.p.x,w.p.y-45,Math.PI/2,60,true);w.step(1/120,{parry:true});assert.equal(b.reflected,true);assert.ok(Math.abs(b.damage-58*1.8)<1e-9);for(let i=0;i<40;i++)w.step(1/120,{});assert.ok(w.covenantStats.reflectedDamage>=58*1.8-.001);});
test('killing the boss is required and ends the encounter even if summoned adds remain',()=>{const w=sign();const boss=w.enemies[0];boss.spawn=0;w.spawn('turret',100,100);w.hitEnemy(boss,boss.hp,'reflect');assert.equal(w.bossKills,1);w.step(1/120,{});assert.equal(w.phase,'won');assert.equal(w.enemies.length,0);assert.equal(w.memoryAfter().honored,1);});
test('memory is bounded and only completed honored fights increment honor; breach counted once',()=>{const w=new V.Run('M','standard',{}, {honored:4,broken:3});assert.deepEqual(w.memoryAfter(),{honored:4,broken:3});w.signCovenant(V.localProposal(w.request('Slow fire')));w.breach();assert.deepEqual(w.memoryAfter(),{honored:4,broken:4});w.phase='won';assert.deepEqual(w.memoryAfter(),{honored:4,broken:4});assert.deepEqual(w.memory,{honored:4,broken:3});});
test('export includes source/revisions/effects, no prompt, access token or invented voice integration',()=>{const w=sign();const r=w.report();assert.equal(r.liveVoice.status,'not-used');assert.equal(r.liveVoice.connectionStarted,0);assert.equal(r.receipts[0].provider,'local-rules');assert.equal(r.receipts[0].revision,1);assert.equal(r.receipts[0].model,null);assert.equal('prompt'in r,false);assert.equal('token'in r,false);assert.equal(r.version,'0.5.0');r.receipts[0].spec.title='external mutation';assert.notEqual(w.spec.title,r.receipts[0].spec.title);});
test('identical seed, signatures and inputs produce identical gameplay counters',()=>{function run(){const w=sign('Sanctuary left. Slow fire. Reinforcements.');w.autoParley=false;for(let i=0;i<2400&&w.phase==='combat';i++){w.step(1/120,{shoot:true,autoAim:true,mx:Math.sin(i/200)*.2,parry:i%115===0,dash:i%290===0});w.takeEvents();}return {...w.report(),receipts:w.receipts.map(r=>({...r,latencyMs:null}))};}assert.deepEqual(run(),run());});
test('baseline center-sanctuary hook remains identical to the old collision condition',()=>{const w=new C.World('CORE');w.mods=C.modifiers('sanctuary');for(let i=0;i<1000;i++){const b={px:i%800,py:(i*17)%900,x:(i*31)%1280,y:(i*41)%800};assert.equal(w.protectBullet(b),C.segmentHit(b.px,b.py,b.x,b.y,640,400,76));}});


test('local keyword fallback follows latest direction and explicit Japanese no-sanctuary terms',()=>{
 const w=new V.Run('LOCAL-CORRECTIONS');
 assert.equal(V.localProposal(w.request('Left, no, right sanctuary. Slow fire; reinforcements.')).zone,'right');
 assert.equal(V.localProposal(w.request('右、いや左を安全に。増援は許可。')).zone,'left');
 const none=V.localProposal(w.request('結界はなし。弾を遅く、反射を強く。通常射撃を弱くしていい'));
 assert.equal(none.zone,'none');assert.equal(none.speed,'slow');assert.equal(none.reflection,'charged');assert.equal(none.price,'weaker_gun');
});
