'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),V=require('../src/covenant.js'),PactSession=require('../src/session.js');
const request=()=>new V.Run('CLIENT-TEST').request('Left sanctuary, slow fire, reinforcements.');
const response=()=>({ok:true,status:200,json:async()=>({provider:'openai',model:'text-model-test-fixture',spec:V.localProposal(request()),requestId:'req-fixture',intentVersion:0})});
const sessionFor=(fetcher)=>new PactSession({fetch:async(path,opts)=>{if(path==='/api/session')return new Response(JSON.stringify({sessionId:'session-fixture',csrf:'csrf-fixture',expiresAt:Date.now()+60000,contractEnabled:true,voiceEnabled:false}),{status:200});return fetcher(path,opts);}});
const serverOpts=(fetcher)=>({mode:'server',consent:true,session:sessionFor(fetcher),runId:'run-fixture',intentVersion:0});
async function hosted(fn){const saved={window:global.window,location:global.location};global.window={NEMESIS_HOSTED:true};global.location={protocol:'https:'};try{return await fn();}finally{for(const [k,v] of Object.entries(saved))if(v===undefined)delete global[k];else global[k]=v;}}
test('local provider makes no network call and labels no AI',async()=>{let calls=0;await hosted(async()=>{const r=await new V.Client().propose(request());assert.equal(r.provider,'local-rules');assert.equal(r.model,null);assert.equal(r.fallback,false);});assert.equal(calls,0);});
test('missing consent and standalone server use fail before session or fetch',async()=>{let calls=0;await hosted(async()=>{await assert.rejects(new V.Client().propose(request(),{mode:'server',consent:false}),/Consent/);window.NEMESIS_HOSTED=false;await assert.rejects(new V.Client().propose(request(),{mode:'server',consent:true}),/hosted/);});assert.equal(calls,0);});
test('fixture response uses session CSRF credentials and no Authorization token',async()=>{let seen;await hosted(async()=>{const r=await new V.Client().propose(request(),serverOpts(async(url,opts)=>{seen={url,opts};return response();}));assert.equal(r.provider,'openai');assert.equal(r.spec.zone,'left');assert.equal(r.model,'text-model-test-fixture');assert.equal(r.intentVersion,0);assert.match(r.requestId,/^[0-9a-f-]{36}$/);});assert.equal(seen.url,'/api/covenant');assert.equal(seen.opts.credentials,'same-origin');assert.equal(seen.opts.headers['X-Nemesis-CSRF'],'csrf-fixture');assert.equal(seen.opts.headers.Authorization,undefined);const body=JSON.parse(seen.opts.body);assert.equal(body.request.seed,'CLIENT-TEST');assert.equal(body.runId,'run-fixture');assert.equal(body.intentVersion,0);});
test('unknown provider, HTTP failure and malformed paid advantages become explicit local fallback',async()=>{for(const fake of [()=>({...response(),status:429,ok:false}),()=>({ok:true,json:async()=>({provider:'fake-ai',spec:V.localProposal(request())})}),()=>({ok:true,json:async()=>({provider:'openai',model:'fixture',spec:{...V.localProposal(request()),price:'weaker_gun'}})})])await hosted(async()=>{const r=await new V.Client().propose(request(),serverOpts(async()=>fake()));assert.equal(r.provider,'local-rules');assert.equal(r.model,null);assert.equal(r.fallback,true);});});
test('cancelled late upstream reply is discarded',async()=>{let release;await hosted(async()=>{const c=new V.Client(),pending=c.propose(request(),serverOpts(()=>new Promise(resolve=>{release=resolve;})));await new Promise(resolve=>setTimeout(resolve,0));c.cancel();release(response());await assert.rejects(pending,/Superseded/);});});
test('second proposal supersedes first even when first fetch ignores abort',async()=>{const release=[];await hosted(async()=>{const c=new V.Client(),p1=c.propose(request(),serverOpts(()=>new Promise(resolve=>release.push(resolve))));await new Promise(resolve=>setTimeout(resolve,0));const p1Handled=assert.rejects(p1,/Superseded/),p2=c.propose(request(),serverOpts(()=>new Promise(resolve=>release.push(resolve))));await new Promise(resolve=>setTimeout(resolve,0));assert.equal(release.length,2);release[1](response());assert.equal((await p2).provider,'openai');release[0](response());await p1Handled;});});
test('aborted connection yields labelled local counteroffer, not OpenAI receipt',async()=>{await hosted(async()=>{const r=await new V.Client().propose(request(),serverOpts(async()=>{throw new DOMException('Test connection aborted','AbortError');}));assert.equal(r.provider,'local-rules');assert.equal(r.fallback,true);assert.match(r.reason,/Timed out|aborted|LOCAL RULES/i);});});
