'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),V=require('../src/covenant.js');
const request=()=>new V.Run('CLIENT-TEST').request('Left sanctuary, slow fire, reinforcements.');
const response=()=>({ok:true,status:200,json:async()=>({provider:'openai',model:'text-model-test-fixture',spec:V.localProposal(request())})});
async function hosted(fn,fetcher){const saved={window:global.window,location:global.location,fetch:global.fetch};global.window={NEMESIS_HOSTED:true};global.location={protocol:'http:'};global.fetch=fetcher;try{return await fn();}finally{for(const [k,v] of Object.entries(saved))if(v===undefined)delete global[k];else global[k]=v;}}
test('covenant client local provider makes no network call and labels no AI',async()=>{let calls=0;await hosted(async()=>{const r=await new V.Client().propose(request());assert.equal(r.provider,'local-rules');assert.equal(r.model,null);assert.equal(r.fallback,false);},async()=>{calls++;throw Error('Not expected');});assert.equal(calls,0);});
test('covenant client rejects missing consent without fetching',async()=>{let calls=0;await hosted(async()=>{await assert.rejects(new V.Client().propose(request(),{mode:'server',consent:false}),/Consent/);},async()=>{calls++;});assert.equal(calls,0);});
test('covenant client refuses standalone server use even with consent',async()=>{await hosted(async()=>{window.NEMESIS_HOSTED=false;await assert.rejects(new V.Client().propose(request(),{mode:'server',consent:true}),/hosted/);},async()=>{throw Error('No request expected');});});
test('covenant client validates fixture response and sends only pilot code to same-origin path',async()=>{let seen;await hosted(async()=>{const r=await new V.Client().propose(request(),{mode:'server',consent:true,token:'pilot-only'});assert.equal(r.provider,'openai');assert.equal(r.spec.zone,'left');assert.equal(r.model,'text-model-test-fixture');assert.equal(r.fallback,false);},async(url,opts)=>{seen={url,opts};return response();});assert.equal(seen.url,'/api/covenant');assert.equal(seen.opts.headers.Authorization,'Bearer pilot-only');assert.equal(JSON.parse(seen.opts.body).seed,'CLIENT-TEST');});
test('unknown provider, HTTP failure and malformed paid advantages become explicit local fallback',async()=>{for(const fake of [()=>({...response(),status:429,ok:false}),()=>({ok:true,json:async()=>({provider:'fake-ai',spec:V.localProposal(request())})}),()=>({ok:true,json:async()=>({provider:'openai',model:'fixture',spec:{...V.localProposal(request()),price:'weaker_gun'}})})])await hosted(async()=>{const r=await new V.Client().propose(request(),{mode:'server',consent:true});assert.equal(r.provider,'local-rules');assert.equal(r.model,null);assert.equal(r.fallback,true);},async()=>fake());});
test('cancelled late upstream reply is discarded, never turned into an applicable fallback',async()=>{let release;await hosted(async()=>{const c=new V.Client(),pending=c.propose(request(),{mode:'server',consent:true});c.cancel();release(response());await assert.rejects(pending,/Superseded/);},()=>new Promise(resolve=>{release=resolve;}));});
test('second proposal supersedes the first even if first fetch ignores its abort signal',async()=>{const release=[];await hosted(async()=>{const c=new V.Client(),p1=c.propose(request(),{mode:'server',consent:true});const p2=c.propose(request(),{mode:'server',consent:true});release[1](response());assert.equal((await p2).provider,'openai');release[0](response());await assert.rejects(p1,/Superseded/);},()=>new Promise(resolve=>release.push(resolve)));});
test('an aborted connection yields a labelled local counteroffer, not an OpenAI receipt',async()=>{await hosted(async()=>{const r=await new V.Client().propose(request(),{mode:'server',consent:true});assert.equal(r.provider,'local-rules');assert.equal(r.fallback,true);assert.match(r.reason,/Timed out/);},async()=>{throw new DOMException('Test connection aborted','AbortError');});});
