'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {createHmac}=require('node:crypto');const D=require('../src/debrief.js');const {createSessionToken}=require('../server/access.mjs');
const env={AI_MODE:'live',TEXT_PROVIDER:'vercel',AI_GATEWAY_API_KEY:'fixture',OPENAI_MODEL:'gpt-5.6-luna',ALLOWED_ORIGIN:'https://fixture.example',APP_SESSION_SECRET:'fixture-session-secret-012345678901234567890123'};
const run=(p={})=>({mode:'classic',outcome:'won',difficulty:'assist',autoplay:false,seconds:30,kills:12,bossKills:1,totalStages:3,parries:2,grazes:3,damageTaken:1,score:900,maxHull:10,hull:9,pactsKept:1,pactsTotal:2,adaptiveLevel:0,upgradeIds:['rail'],relicIds:['needle'],pactIds:['mercy'],...p});const input=(p={})=>({runId:'server-run',sequence:1,language:'en',run:run(p)});
function request(body,origin=env.ALLOWED_ORIGIN){const sid='debrief-session',exp=Math.floor(Date.now()/1000)+900,csrf=createHmac('sha256',env.APP_SESSION_SECRET).update(`csrf:${sid}:${exp}`).digest('base64url');return new Request('https://fixture.example/api/debrief',{method:'POST',headers:{'content-type':'application/json',origin,cookie:`nemesis_app_session=${createSessionToken({secret:env.APP_SESSION_SECRET,sid,exp})}`,'x-nemesis-csrf':csrf},body:JSON.stringify(body)});}
function fixtures({deny=false}={}){const states=new Map(),calls=[];return {calls,store:{eval:async(script,keys,args)=>{const k=keys[0],s=states.get(k)||{sequence:0};if(script.includes('pending=true')){const n=+args[0];if(n<=s.sequence)return [0,n===s.sequence&&s.digest===args[1]?'duplicate':'stale',JSON.stringify(s)];states.set(k,{sequence:n,digest:args[1],pending:true});return [1,'started',''];}if(script.includes('return 0')){states.delete(k);return 1;}const n=+args[0];if(s.sequence!==n||s.digest!==args[1]||!s.pending)return [0,'stale'];s.pending=false;s.result=JSON.parse(args[2]);states.set(k,s);return [1,'saved'];}},quota:{reserve:async x=>{calls.push(['reserve',x]);return deny?{ok:false,reservationId:'denied-res'}:{ok:true,reservationId:'debrief-res'}},markStarted:async()=>{calls.push(['start']);return {ok:true}},settle:async x=>{calls.push(['settle',x]);return {ok:true}}}};}
const upstream=(decision=D.mock(input()))=>Response.json({status:'completed',usage:{input_tokens:100,output_tokens:100},output:[{content:[{type:'output_text',text:JSON.stringify(decision)}]}]});
test('deployment aliases require session and legacy path stays offline within 12 functions',async()=>{
 const {POST}=await import('../api/intelligence.mjs');
 const prior=Object.fromEntries(Object.keys(env).map(k=>[k,process.env[k]]));Object.assign(process.env,env);
 try{
  for(const path of ['/api/debrief','/api/intelligence?operation=debrief']){
   const r=await POST(new Request('https://fixture.example'+path,{method:'POST',headers:{origin:env.ALLOWED_ORIGIN,'content-type':'application/json'},body:JSON.stringify({request:input()})}));
   assert.equal(r.status,401);
  }
  const r=await POST(new Request('https://fixture.example/api/intelligence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({task:'debrief',prompt:'',seed:'fixture',stage:0,allowed:['mercy'],telemetry:{}})}));
  const data=await r.json();assert.notEqual(data.provider,'openai');
  const fs=require('node:fs'),path=require('node:path');
  const files=(dir)=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.isDirectory()?files(path.join(dir,x.name)):[x.name]);
  assert.ok(files('api').filter(x=>x.endsWith('.mjs')).length<=12);
  const config=JSON.parse(fs.readFileSync('vercel.json','utf8'));
  assert.deepEqual(config.rewrites.find(x=>x.source==='/api/debrief'),{source:'/api/debrief',destination:'/api/intelligence?operation=debrief'});
 }finally{for(const [k,v]of Object.entries(prior)){if(v===undefined)delete process.env[k];else process.env[k]=v;}}
});
test('authorization and kill switch prevent upstream',async()=>{const {handle}=await import('../server/debrief.mjs');const f=fixtures();assert.ok((await handle(request({request:input()} ,'https://bad.example'),{env,...f,fetcher:()=>{throw Error('called')}})).status>=400);const r=await handle(request({request:input()}),{env:{...env,OPENAI_KILL_SWITCH:'1'},...f,fetcher:()=>{throw Error('called')}});assert.ok(r.status>=400);});
test('quota rejection aborts pending state and retry same sequence can run',async()=>{const {handle}=await import('../server/debrief.mjs');const f=fixtures({deny:true});assert.equal((await handle(request({request:input()}),{env,...f,fetcher:()=>{throw Error('called')}})).status,429);f.quota.reserve=async x=>{f.calls.push(['reserve',x]);return {ok:true,reservationId:'retry-res'}};assert.equal((await handle(request({request:input()}),{env,...f,fetcher:async()=>upstream()})).status,200);});
test('duplicate cache uses one upstream and missing usage keeps reservation',async()=>{const {handle}=await import('../server/debrief.mjs');const f=fixtures();let n=0;const o={env,...f,fetcher:async()=>{n++;return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(D.mock(input()))}]}]})}};const a=await(await handle(request({request:input()}),o)).json(),b=await(await handle(request({request:input()}),o)).json();assert.equal(n,1);assert.equal(b.deduplicated,true);assert.equal(a.accountedMicrodollars,10000);});
test('duplicate while first is pending cannot clear owner state',async()=>{const {handle}=await import('../server/debrief.mjs');const f=fixtures();let release;const first=handle(request({request:input()}),{env,...f,fetcher:async()=>new Promise(r=>{release=r})});await new Promise(r=>setImmediate(r));assert.equal((await handle(request({request:input()}),{env,...f,fetcher:()=>{throw Error('duplicate called')}})).status,409);release(upstream());assert.equal((await first).status,200);assert.equal(f.calls.filter(x=>x[0]==='reserve').length,1);});
test('structured upstream fixture is validated and metadata matches',async()=>{const {handle}=await import('../server/debrief.mjs');const f=fixtures();const clean=input();clean.language='ja';const d=D.mock(clean);let sent;const r=await handle(request({request:clean}),{env,...f,fetcher:async(_u,o)=>{sent=JSON.parse(o.body);return upstream(d)}});const out=await r.json();assert.equal(r.status,200);assert.equal(out.provider,'openai');assert.equal(out.model,'gpt-5.6-luna');assert.equal(out.decision.headline,'飛行完了');assert.equal(sent.input[0].role,'user');assert.equal(sent.input[0].content.includes('runId'),false);});
