'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const D=require('../src/debrief.js'),Client=require('../src/debrief-client.js');
const run=(p={})=>({mode:'classic',outcome:'won',difficulty:'assist',autoplay:false,seconds:30,kills:12,bossKills:1,totalStages:3,parries:2,grazes:3,damageTaken:1,score:900,maxHull:10,hull:9,pactsKept:1,pactsTotal:2,adaptiveLevel:0,upgradeIds:['rail'],relicIds:['needle'],pactIds:['mercy','mirror'],...p});
const req=(p={})=>({runId:'123e4567-e89b-12d3-a456-426614174000',sequence:1,language:'en',run:run(p)});
test('protocol bounds canonical run and preserves values',()=>{const x=D.cleanRequest(req());assert.equal(x.run.score,900);assert.deepEqual(x.run.upgradeIds,['rail']);assert.throws(()=>D.cleanRequest(req({upgradeIds:['raw-prompt']})));assert.throws(()=>D.cleanRequest(req({totalStages:6})));assert.throws(()=>D.cleanRequest(req({outcome:'active'})));});
test('fromWorld requires finished outcome and derives pact counts',()=>{const w={mode:'expedition',phase:'dead',difficulty:'veteran',time:12.4,kills:4,bossKills:0,totalStages:6,parries:1,grazes:2,damageTaken:3,score:4,p:{hp:5,maxHp:10},contracts:[{id:'mercy',kept:true},{id:'mirror',kept:false}],upgrades:{rail:1},relics:['lens']};const x=D.fromWorld(w,{runId:'world-1',sequence:2,language:'ja'});assert.equal(x.run.outcome,'dead');assert.equal(x.run.pactsKept,1);assert.equal(x.run.pactsTotal,2);assert.equal(D.mock(x).headline,'飛行記録');assert.throws(()=>D.fromWorld({...w,phase:'combat'}));});
test('client rejects cancelled stale and wrong model responses',async()=>{let resolve,body;const s={ensure:async()=>{},request:async(_p,b)=>{body=b;return new Promise(r=>resolve=r)}};const c=new Client(s);c.open('client-run');const p=c.request({...req(),run:req().run},true);await new Promise(r=>setImmediate(r));assert.equal(body.request.run.mode,'classic');c.cancel();resolve(Response.json({provider:'openai',model:'wrong',runId:'client-run',sequence:1,decision:D.mock(req())}));await assert.rejects(p,/Superseded/);});
test('client timeout falls back without another fetch',async()=>{let calls=0;const c=new Client({ensure:async()=>{},request:async(_p,_b,o)=>{calls++;return new Promise((_,rej)=>o.signal.addEventListener('abort',()=>rej(Error('aborted'))))}});c.open('timeout-run');const old=globalThis.setTimeout;globalThis.setTimeout=(fn,ms)=>ms===18000?old(fn,1):old(fn,ms);const x=await c.request(req(),true);globalThis.setTimeout=old;assert.equal(x.provider,'local-rules');assert.equal(calls,1);});
test('timeout during session acquisition never starts inference',async()=>{
 let calls=0;const old=globalThis.setTimeout;
 const c=new Client({ensure:async()=>new Promise(r=>old(r,10)),request:async()=>{calls++;throw Error('unexpected');}});c.open('slow-session');
 globalThis.setTimeout=(fn,ms)=>ms===18000?old(fn,1):old(fn,ms);
 try{assert.equal((await c.request(req(),true)).provider,'local-rules');assert.equal(calls,0);}finally{globalThis.setTimeout=old;}
});
