const test=require('node:test');const assert=require('node:assert/strict');const DemoRecorder=require('../src/demo.js').DemoRecorder;
const fakeDoc=()=>({createElement:()=>({addEventListener(){},click(){}}),body:{append(){}},defaultView:{addEventListener(){}}});
test('demo recorder is disabled without explicit demo query',()=>{const d=new DemoRecorder({document:{body:{append(){throw Error('must not attach');}}}});assert.equal(d.attach(),false);});
test('manual recording has no forced timer and saves after an arbitrary duration',async()=>{let stopped=0,interval;const video={kind:'video',readyState:'live',addEventListener(){},stop(){stopped++}};const display={getVideoTracks:()=>[video],getAudioTracks:()=>[],getTracks:()=>[video]};class MS{constructor(tracks){this.tracks=tracks}getAudioTracks(){return this.tracks.filter(t=>t.kind==='audio')}getVideoTracks(){return this.tracks.filter(t=>t.kind==='video')}getTracks(){return this.tracks}}class MR{static isTypeSupported(){return false}constructor(){this.state='inactive';this.mimeType='video/webm';this.listeners={}}addEventListener(k,f){this.listeners[k]=f}start(){this.state='recording'}stop(){this.state='inactive';this.listeners.stop?.()}};const d=new DemoRecorder({navigator:{mediaDevices:{getDisplayMedia:async()=>display}},MediaRecorder:MR,MediaStream:MS,document:fakeDoc(),setInterval:(f)=>{interval=f;return 1},clearInterval(){},setTimeout,clearTimeout});assert.equal(await d.start(),true);assert.equal(d.countdown!==null,true);d.startedAt=Date.now()-65000;interval();assert.equal(d.button,null);assert.equal(d._formatElapsed(3661000),'61:01');assert.equal(d.stop('user'),true);assert.equal(stopped,1);assert.equal(d.state,'stopped');});
test('duplicate stop is ignored and cleanup runs once',async()=>{let stops=0,closes=0;const track={kind:'video',readyState:'live',addEventListener(){},stop(){stops++}};const display={getVideoTracks:()=>[track],getAudioTracks:()=>[],getTracks:()=>[track]};class MR{constructor(){this.state='inactive';this.listeners={};this.mimeType='video/webm'}addEventListener(k,f){this.listeners[k]=f}start(){this.state='recording'}stop(){this.state='inactive';this.listeners.stop?.()}}class MS{constructor(t){this.t=t}getTracks(){return this.t}getVideoTracks(){return this.t}getAudioTracks(){return []}}class AC{createMediaStreamDestination(){return {stream:{getAudioTracks:()=>[]}}}close(){closes++}}const d=new DemoRecorder({navigator:{mediaDevices:{getDisplayMedia:async()=>display}},MediaRecorder:MR,MediaStream:MS,AudioContext:AC,document:fakeDoc(),setInterval:()=>1,clearInterval(){},setTimeout,clearTimeout});assert.equal(await d.start(),true);assert.equal(d.stop(),true);assert.equal(d.stop(),false);assert.equal(stops,1);assert.equal(closes,1);});
test('stop while share dialog is pending cancels the eventual stream',async()=>{let resolveShare,stopped=0;const track={stop(){stopped++}};const display={getTracks:()=>[track],getVideoTracks:()=>[track],getAudioTracks:()=>[]};const d=new DemoRecorder({navigator:{mediaDevices:{getDisplayMedia:()=>new Promise(r=>resolveShare=r)}},MediaRecorder:class{},document:fakeDoc()});const pending=d.start();assert.equal(d.stop('user'),true);resolveShare(display);assert.equal(await pending,false);assert.equal(stopped,1);});
test('tab audio and microphone are mixed, output is added only without tab audio',()=>{const connected=[];class Source{constructor(stream){this.stream=stream}connect(dest){connected.push([this.stream,dest])}}class AC{createMediaStreamDestination(){return {stream:{getAudioTracks:()=>[{kind:'audio',readyState:'live'}]}}}createMediaStreamSource(s){return new Source(s)}close(){}}const track=k=>({kind:k,readyState:'live',stop(){}}),video=track('video'),tab=track('audio'),mic={getAudioTracks:()=>[track('audio')]},enemy={getAudioTracks:()=>[track('audio')]};const d=new DemoRecorder({AudioContext:AC,MediaStream:class{constructor(t){this.t=t}},document:{}});d.display={getVideoTracks:()=>[video],getAudioTracks:()=>[tab]};d.attachVoice(mic,'input');d.attachVoice(enemy,'output');assert.ok(d._buildAudio(0));assert.equal(connected.length,2);assert.equal(connected[0][0],d.display);assert.equal(connected[1][0],mic);});
test('attachVoice does not stop or clone game-owned tracks',()=>{let stopped=0;const track={stop:()=>stopped++};const stream={getAudioTracks:()=>[track]};const d=new DemoRecorder();assert.equal(d.attachVoice(stream,'input'),true);assert.equal(d.voice.input,stream);assert.equal(stopped,0);});

function lifecycleFixture({delayedResume=false}={}){
 const tracks=[],contexts=[],recorders=[];let resume,options;
 const track=kind=>{const t={kind,readyState:'live',stops:0,addEventListener(){},removeEventListener(){},stop(){this.readyState='ended';this.stops++}};tracks.push(t);return t;};
 class MS{constructor(t){this.t=t}getTracks(){return this.t}getVideoTracks(){return this.t.filter(t=>t.kind==='video')}getAudioTracks(){return this.t.filter(t=>t.kind==='audio')}}
 class AC{constructor(){this.closes=0;contexts.push(this)}createMediaStreamDestination(){return {stream:new MS([track('audio')])}}resume(){return delayedResume&&contexts.length===1?new Promise(r=>resume=r):Promise.resolve()}close(){this.closes++;return Promise.resolve()}}
 class MR{constructor(stream,opts){this.state='inactive';this.listeners={};this.mimeType='video/webm';recorders.push(this);assert.equal(opts.videoBitsPerSecond,12000000)}addEventListener(k,f){this.listeners[k]=f}start(){this.state='recording'}stop(){this.state='inactive'}finish(){this.listeners.stop()}}
 const d=new DemoRecorder({navigator:{mediaDevices:{getDisplayMedia:async opts=>{options=opts;return new MS([track('video')])}}},MediaRecorder:MR,MediaStream:MS,AudioContext:AC,document:fakeDoc(),setInterval:()=>1,clearInterval(){},setTimeout:()=>1});
 return {d,tracks,contexts,recorders,resume:()=>resume(),options:()=>options};
}
test('async save prevents a new capture until stop completes, then permits restart',async()=>{
 const f=lifecycleFixture();f.d.button={};await f.d.start();assert.equal(f.options().video.frameRate,60);
 assert.equal(f.d.stop(),true);assert.equal(f.d.button.disabled,true);assert.equal(f.d.button.textContent,'Saving…');
 assert.equal(await f.d.start(),false);assert.equal(f.d.stop(),false);f.recorders[0].finish();
 assert.ok(f.tracks.every(t=>t.stops===1));assert.equal(f.contexts[0].closes,1);
 assert.equal(await f.d.start(),true);f.recorders[0].finish();assert.equal(f.d.state,'recording');
 f.d.stop();f.recorders[1].finish();assert.ok(f.tracks.every(t=>t.stops===1));
});
test('cancel during audio resume ends owned tracks; its late result cannot close a new capture',async()=>{
 const f=lifecycleFixture({delayedResume:true});const first=f.d.start();await Promise.resolve();await Promise.resolve();
 f.d.stop('pagehide');assert.equal(f.d.state,'idle');assert.ok(f.tracks.every(t=>t.stops===1));assert.equal(f.contexts[0].closes,1);
 assert.equal(await f.d.start(),true);f.resume();assert.equal(await first,false);assert.equal(f.d.state,'recording');assert.equal(f.contexts[1].closes,0);
 f.d.stop();f.recorders[0].finish();assert.ok(f.tracks.every(t=>t.stops===1));
});
