'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{createHmac}=require('node:crypto');
const I=require('../src/intelligence.js'),Client=require('../src/director-client.js'),X=require('../src/expansion.js');
const {createSessionToken}=require('../server/access.mjs');
const env={AI_MODE:'live',TEXT_PROVIDER:'vercel',AI_GATEWAY_API_KEY:'fixture-only-key',OPENAI_MODEL:'gpt-5.6-luna',ALLOWED_ORIGIN:'https://fixture.example',APP_SESSION_SECRET:'fixture-session-secret-012345678901234567890123'};
const input=()=>({task:'director',prompt:'Crossfire with fair gaps',seed:'DIRECTOR',stage:0,allowed:I.CONTRACTS,telemetry:{kills:12,damageTaken:4}});
const body=()=>({request:input(),runId:'director-run',requestId:'director-req',intentVersion:2});
function req(data=body(),extra={}){const sid='director-session',exp=Math.floor(Date.now()/1000)+900;const csrf=createHmac('sha256',env.APP_SESSION_SECRET).update(`csrf:${sid}:${exp}`).digest('base64url');return new Request('https://fixture.example/api/director',{method:'POST',headers:{'Content-Type':'application/json',origin:env.ALLOWED_ORIGIN,cookie:`nemesis_app_session=${createSessionToken({secret:env.APP_SESSION_SECRET,sid,exp})}`,'x-nemesis-csrf':csrf,...extra},body:JSON.stringify(data)});}
function fixtures(){const calls=[],actions=[],states=new Map();return {calls,actions,store:{eval:async(_lua,keys,args)=>{const a=JSON.parse(args[0]);actions.push(a);assert.match(keys[0],/^nemesis:director:/);let s=states.get(keys[0])||{revision:0,intent:-1};if(a.op==='begin'){if(a.revision!==s.revision||a.intent<=s.intent)return [0,'stale'];s={...s,intent:a.intent,requestId:a.requestId,proposal:null};}else if(a.op==='invalidate'){if(a.intent>s.intent)s={...s,intent:a.intent,proposal:null,requestId:null};}else if(a.op==='finish'){if(a.intent!==s.intent||a.requestId!==s.requestId||s.proposal)return [0,'stale'];s.proposal=a.proposal;}else if(a.op==='sign'){if(a.revision!==s.revision||a.intent!==s.intent||!s.proposal||a.proposalId!==s.proposal.proposalId||a.digest!==s.proposal.digest)return [0,'stale'];s={...s,revision:s.revision+1,signed:s.proposal,proposal:null};}states.set(keys[0],s);return [1,JSON.stringify(s)];}},quota:{reserve:async a=>{calls.push(['reserve',a]);return {ok:true,reservationId:'fixture-res'};},markStarted:async()=>{calls.push(['started']);return {ok:true};},settle:async a=>{calls.push(['settle',a]);return {ok:true};}}};}
function upstream(decision=I.mock(input())){return Response.json({status:'completed',usage:{input_tokens:100,output_tokens:100},output:[{content:[{type:'output_text',text:JSON.stringify(decision)}]}]});}
test('director requires origin, CSRF and app session; rejects other tasks and arbitrary fields before spending',async()=>{const {handle}=await import('../server/director.mjs');let n=0;for(const headers of [{origin:'https://wrong.example'},{cookie:''},{'x-nemesis-csrf':'wrong'}]){assert.ok((await handle(req(body(),headers),{env,...fixtures(),fetcher:()=>{n++;}})).status>=400);}for(const data of [{...body(),extra:1},{...body(),request:{...input(),task:'debrief'}},{...body(),request:{...input(),stage:6}}])assert.equal((await handle(req(data),{env,...fixtures(),fetcher:()=>{n++;}})).status,400);assert.equal(n,0);});
test('director uses Luna, strict schema, standard tier and the shared conservative reservation',async()=>{const {handle}=await import('../server/director.mjs');const f=fixtures();let payload,url;const r=await handle(req(),{env,...f,fetcher:async(u,o)=>{url=u;payload=JSON.parse(o.body);return upstream();}}),v=await r.json();assert.equal(v.provider,'openai');assert.equal(v.model,'gpt-5.6-luna');assert.equal(v.decision.directorId,'crossfire');assert.equal(url,'https://ai-gateway.vercel.sh/v1/responses');assert.equal(payload.model,'openai/gpt-5.6-luna');assert.equal(payload.reasoning.effort,'none');assert.equal(payload.service_tier,'default');assert.equal(payload.store,false);assert.equal(payload.text.format.strict,true);assert.equal(f.calls[0][1].kind,'text');assert.equal(f.calls[0][1].estimatedMicrodollars,10000);assert.equal(v.accountedMicrodollars,145);assert.doesNotMatch(JSON.stringify(v),/fixture-only-key/);});
test('offline, kill and exhausted budget never call inference',async()=>{const {handle}=await import('../server/director.mjs');let n=0;const fetcher=()=>{n++;};assert.equal((await(await handle(req(),{env:{AI_MODE:'mock'},fetcher})).json()).provider,'local-rules');assert.equal((await handle(req(),{env:{...env,OPENAI_KILL_SWITCH:'1'},fetcher,...fixtures()})).status,503);assert.equal((await handle(req(),{env,fetcher,...fixtures(),quota:{reserve:async()=>({ok:false})}})).status,429);assert.equal(n,0);});
test('transport failure and invalid model output produce local proposals and retain unreported spend',async()=>{const {handle}=await import('../server/director.mjs');for(const fetcher of [async()=>{throw Error('Offline');},async()=>upstream({...I.mock(input()),directorId:'god-mode'})]){const f=fixtures(),v=await(await handle(req(),{env,...f,fetcher})).json();assert.equal(v.provider,'local-rules');assert.match(v.reason,/LOCAL RULES/);assert.ok(I.validateDecision(v.decision,input()));assert.ok(f.calls.find(c=>c[0]==='settle'));}const f=fixtures();await handle(req(),{env,...f,fetcher:async()=>{throw Error('Offline');}});assert.equal(f.calls.at(-1)[1].actualMicrodollars,10000);});
test('late result after cancel cannot publish and paid work is still accounted',async()=>{const {handle,control}=await import('../server/director.mjs'),f=fixtures();let release,started;const ready=new Promise(r=>started=r);const pending=handle(req(),{env,...f,fetcher:async()=>{started();return new Promise(r=>release=r);}});await ready;assert.equal((await control(req({runId:'director-run',intentVersion:3}),'cancel',{env,...f})).status,200);release(upstream());assert.equal((await pending).status,409);assert.ok(f.calls.find(c=>c[0]==='settle'));});
test('approval digest and intent are bound; simultaneous double approval succeeds only once',async()=>{const {handle,control}=await import('../server/director.mjs'),f=fixtures();const p=await(await handle(req(),{env,...f,fetcher:async()=>upstream()})).json();const s={runId:'director-run',intentVersion:2,revision:0,proposalId:p.proposalId,digest:p.digest};assert.equal((await control(req({...s,digest:'wrong'}),'sign',{env,...f})).status,409);const results=await Promise.all([control(req(s),'sign',{env,...f}),control(req(s),'sign',{env,...f})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);});
test('client invalidates edits and stale responses, uses newer intent after cancellation and never applies twice',async()=>{let resolve,lastBody;const session={csrf:'fixture',ensure:async()=>{},request:async(path,b)=>{if(path.endsWith('/cancel'))return Response.json({});lastBody=b;return new Promise(r=>resolve=r);}};const c=new Client(session);c.open();let pending=c.request(input(),true);await new Promise(r=>setImmediate(r));c.cancel();resolve(Response.json({provider:'openai',model:'gpt-5.6-luna',decision:I.mock(input()),proposalId:'proposal-id',digest:'digest',requestId:lastBody.requestId,intentVersion:lastBody.intentVersion}));await assert.rejects(pending,/Superseded/);const canceledIntent=c.intentVersion;pending=c.request(input(),true);await new Promise(r=>setImmediate(r));assert.ok(lastBody.intentVersion>canceledIntent);resolve(Response.json({provider:'local-rules',decision:I.mock(input())}));await pending;assert.equal((await c.apply()).decision.directorId,'crossfire');await assert.rejects(c.apply());});
test('client sign requires matching server receipt and exiting during approval cannot apply',async()=>{let resolve;const session={csrf:'fixture',ensure:async()=>{},request:async(path,b)=>{if(path.endsWith('/cancel'))return Response.json({});if(path.endsWith('/sign'))return new Promise(r=>resolve=r);return Response.json({provider:'openai',model:'gpt-5.6-luna',decision:I.mock(input()),proposalId:'proposal-id',digest:'digest',requestId:b.requestId,intentVersion:b.intentVersion});}};const c=new Client(session);c.open();await c.request(input(),true);const pending=c.apply();await assert.rejects(c.apply());c.close();resolve(Response.json({signed:true,revision:1,proposalId:'proposal-id',digest:'digest',decision:I.mock(input())}));await assert.rejects(pending,/changed/);});
test('formation preview is immutable and byte-identical to launched wave across all sectors/routes/directors',()=>{for(let stage=0;stage<6;stage++)for(const route of X.ROUTES)for(const id of I.DIRECTORS){const w=new X.Run('DIRECTOR','standard');w.stage=stage;const before=JSON.stringify(w);const plan=w.formationPlan(id,route.id);assert.equal(JSON.stringify(w),before);assert.ok(plan.length<=36);w.setDirector(id);w.chooseRoute(route.id);w.sign(w.offersForPact()[0].id);assert.deepEqual(w.wavePlan,plan);assert.equal(w.setDirector('balanced'),false);}for(const mode of ['classic','gauntlet'])assert.equal(new X.Run('DIRECTOR','standard',false,{}, {mode}).setDirector('pursuit'),false);});
test('applying director preserves hull, time, credits and pact while invalid catalog IDs reject',()=>{const w=new X.Run('DIRECTOR','standard');w.p.hp=4;w.time=52;const before={hp:w.p.hp,time:w.time,credits:w.credits,pact:w.pact};assert.equal(w.setDirector('__proto__'),false);assert.ok(w.setDirector('pursuit'));assert.deepEqual({hp:w.p.hp,time:w.time,credits:w.credits,pact:w.pact},before);});
