// Handler integration: actual isolated Redis, fixture model; never production accounting keys.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createHmac,randomUUID} from 'node:crypto';
import {createRedisRestStore} from '../server/quota.mjs';import {createSessionToken} from '../server/access.mjs';
import {handle as covenant} from '../server/covenant.mjs';import {handle as control} from '../server/controls.mjs';import V from '../src/covenant.js';
const url=process.env.KV_REST_API_URL,token=process.env.KV_REST_API_TOKEN;
const secret='handler-test-secret-'.repeat(3),origin='https://nemesis.example',sid=randomUUID(),exp=Math.floor(Date.now()/1000)+900;
const env={AI_MODE:'live',OPENAI_API_KEY:'fixture-only',OPENAI_MODEL:'gpt-4.1-mini',OPENAI_BUDGET_CAP_MICRODOLLARS:'1000000',OPENAI_POOL_VERIFICATION_CAP_MICRODOLLARS:'1000000',OPENAI_POOL_PUBLIC_CAP_MICRODOLLARS:'0',OPENAI_POOL_JUDGING_CAP_MICRODOLLARS:'0',OPENAI_TEXT_BUDGET_CAP_MICRODOLLARS:'1000000',OPENAI_VOICE_BUDGET_CAP_MICRODOLLARS:'0',OPENAI_MAX_CONCURRENT:'4',APP_SESSION_SECRET:secret,ALLOWED_ORIGIN:origin};
function isolated(base){const prefix=`nemesis:test:handlers:${randomUUID()}:`,keys=new Set();const map=key=>{const k=String(key).startsWith(prefix)?String(key):prefix+String(key);keys.add(k);return k;};return {async eval(script,ks,args){return base.eval(script,ks.map(map),args);},async get(k){return base.get(map(k));},async set(k,v){return base.command(['SET',map(k),v]);},async command(parts){const cmd=String(parts[0]).toUpperCase();if(cmd==='DEL')return base.command([cmd,...parts.slice(1).map(map)]);if(['SET','GET','HGETALL','TTL'].includes(cmd))return base.command([cmd,map(parts[1]),...parts.slice(2)]);throw Error('Unsupported isolated test command');},async cleanup(){for(const k of keys){assert.ok(k.startsWith(prefix));await base.command(['DEL',k]);}},count:()=>keys.size};}
function req(body,who=sid){const cookie=createSessionToken({secret,sid:who,exp}),csrf=createHmac('sha256',secret).update(`csrf:${who}:${exp}`).digest('base64url');return new Request(origin+'/api/covenant',{method:'POST',headers:{origin,'content-type':'application/json',cookie:`nemesis_app_session=${cookie}`,'x-nemesis-csrf':csrf},body:JSON.stringify(body)});}
const input=(runId,intentVersion=1)=>({request:new V.Run('HANDLER-TEST').request('Left sanctuary and slow bullets; allow reinforcements'),runId,requestId:randomUUID(),intentVersion});
const modelResult={status:'completed',usage:{input_tokens:10,output_tokens:10},output:[{content:[{type:'output_text',text:JSON.stringify({version:1,title:'Test left',line:'Read the clauses.',rationale:'Fixture only.',zone:'left',speed:'slow',reflection:'normal',price:'reinforcements'})}]}]};
const signing=(runId,p)=>({runId,intentVersion:p.intentVersion,revision:0,proposalId:p.proposalId,digest:p.digest});
test('actual Redis enforces handler signature, ownership, cancellation and late completion',{skip:!url||!token},async()=>{
 const store=isolated(createRedisRestStore({url,token}));let fixtureCalls=0;const fetcher=async()=>{fixtureCalls++;return new Response(JSON.stringify(modelResult));};const checks=[];
 const make=async id=>{const r=await covenant(req(input(id)),{env,store,fetcher});assert.equal(r.status,200);const p=await r.json();assert.equal(p.provider,'openai');return p;};
 try{
  const id=randomUUID(),p=await make(id),body=signing(id,p);
  const bad=await control(req({...body,digest:'wrong-digest'}),'sign',{env,store});assert.equal(bad.status,409);
  const foreign=await control(req(body,randomUUID()),'sign',{env,store});assert.equal(foreign.status,409);checks.push('wrong digest and different authenticated owner rejected');
  const statuses=await Promise.all(Array.from({length:8},async()=>{const r=await control(req(body),'sign',{env,store});if(r.status===200){const signed=await r.json();assert.equal(signed.revision,1);assert.equal(signed.digest,p.digest);assert.deepEqual(signed.spec,p.spec);}return r.status;}));assert.equal(statuses.filter(s=>s===200).length,1);assert.equal(statuses.filter(s=>s===409).length,7);checks.push('eight parallel Sign requests: exactly one applies canonical revision 1');
  const cancelId=randomUUID(),cancelP=await make(cancelId);assert.equal((await control(req({runId:cancelId,intentVersion:2}),'cancel',{env,store})).status,200);assert.equal((await control(req(signing(cancelId,cancelP)),'sign',{env,store})).status,409);checks.push('cancel invalidates unsigned proposal before signature');
  let release,entered;const reached=new Promise(r=>entered=r),lateId=randomUUID();const late=covenant(req(input(lateId)),{env,store,fetcher:async()=>{fixtureCalls++;entered();await new Promise(r=>release=r);return new Response(JSON.stringify(modelResult));}});await reached;assert.equal((await control(req({runId:lateId,intentVersion:2}),'cancel',{env,store})).status,200);release();assert.equal((await late).status,409);checks.push('model response arriving after cancel cannot publish stale proposal');
  const report={checkedAt:new Date().toISOString(),passed:true,store:'actual Upstash Redis',quota:'actual reserve/settle Lua in isolated namespace',model:'fixture only',realModelCalls:0,fixtureCalls,productionKeysMutated:false,parallelSignStatuses:statuses,checks,isolatedKeyCount:store.count()};fs.mkdirSync('docs/validation-current/handler-redis',{recursive:true});fs.writeFileSync('docs/validation-current/handler-redis/result.json',JSON.stringify(report,null,2));
 }finally{await store.cleanup();}
});
