import test from 'node:test';import assert from 'node:assert/strict';import {createQuota,createRedisRestStore,LUA} from '../server/quota.mjs';
const env={OPENAI_BUDGET_CAP_MICRODOLLARS:'1000',OPENAI_POOL_VERIFICATION_CAP_MICRODOLLARS:'500',OPENAI_POOL_PUBLIC_CAP_MICRODOLLARS:'300',OPENAI_POOL_JUDGING_CAP_MICRODOLLARS:'200',OPENAI_TEXT_BUDGET_CAP_MICRODOLLARS:'700',OPENAI_VOICE_BUDGET_CAP_MICRODOLLARS:'300',OPENAI_MAX_CONCURRENT:'2'};
test('fails closed without durable store or explicit allocation',()=>{assert.throws(()=>createQuota({env}),/Durable/);assert.throws(()=>createQuota({env:{...env,OPENAI_POOL_PUBLIC_CAP_MICRODOLLARS:''},store:{eval(){}}}),/Explicit/) });
test('reserve validates identity and voice duration',async()=>{const calls=[];const store={eval:async(s,k,a)=>{calls.push({s,k,a});return[1,'reserved']}};const q=createQuota({store,env});await assert.rejects(q.reserve({reservationId:'bad/id',sid:'s',ip:'x',estimatedMicrodollars:1}),/Invalid quota identity/);await assert.rejects(q.reserve({reservationId:'r',sid:'s',ip:'x',estimatedMicrodollars:1,kind:'voice',seconds:46}),/Invalid reservation/);const out=await q.reserve({reservationId:'r',sid:'s',ip:'x',estimatedMicrodollars:10,kind:'voice',pool:'judging',seconds:45});assert.equal(out.ok,true);const p=JSON.parse(calls[0].a[0]);assert.equal(p.kind,'voice');assert.equal(p.pool,'judging')});
test('lifecycle and REST errors are exposed',async()=>{const q=createQuota({store:{eval:async()=>[1,'ok'],set:async()=>{}},env});assert.equal((await q.markStarted({reservationId:'r'})).ok,true);assert.equal((await q.retainUnknown({reservationId:'r'})).ok,true);assert.equal((await q.settle({reservationId:'r',actualMicrodollars:1,terminationConfirmed:true})).ok,true);const s=createRedisRestStore({url:'https://redis.invalid',token:'x',fetcher:async()=>new Response(JSON.stringify({error:'denied'}),{status:200})});await assert.rejects(s.command(['GET','x']),/Quota store unavailable/)});
test('Lua exports contain atomic reservation and transitions',()=>{assert.match(LUA.RESERVE_LUA,/HINCRBY/);assert.match(LUA.TRANSITION_LUA,/state/);assert.match(LUA.SESSION_LUA,/issue_limit/)})

test('voice allowance is scoped to a run while identity, budget and active lock remain shared',async()=>{
 const keys=[];const q=createQuota({env,store:{eval:async(script,k)=>{keys.push(k);return[1,'reserved'];}}});
 for(const runId of ['first-fight','second-fight',undefined])await q.reserve({reservationId:'reservation'+keys.length,sid:'same-session',ip:'same-ip',kind:'voice',runId,estimatedMicrodollars:10});
 assert.equal(keys[0][0],keys[1][0]);assert.equal(keys[0][2],keys[1][2]);assert.equal(keys[0][4],keys[1][4]);assert.equal(keys[0][6],keys[1][6]);assert.notEqual(keys[0][7],keys[1][7]);assert.equal(keys[2][7],keys[2][2]);
});

test('campaign admission remains bounded at 48 shared paid calls and 20 per IP minute',async()=>{let data;const q=createQuota({env,store:{eval:async(_s,_k,args)=>{data=JSON.parse(args[0]);return[1,'reserved'];}}});await q.reserve({reservationId:'bounded',sid:'s',ip:'ip',estimatedMicrodollars:1});assert.equal(data.sessionCalls,48);assert.equal(data.ipCalls,20);assert.equal(data.maxConcurrent,2);});
