/* Shared, authored campaign catalog. The AI may select an offer, never define one. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./core.js'):root.PactCore,typeof module==='object'&&module.exports?require('./expansion.js'):root.PactExpansion,typeof module==='object'&&module.exports?require('./intelligence.js'):root.PactIntelligence);if(typeof module==='object'&&module.exports)module.exports=api;else root.PactCampaign=api;})(typeof globalThis!=='undefined'?globalThis:this,function(C,X,I){'use strict';
 const MODES=['expedition','gauntlet','classic'];
 const EXPANSION=[['mercy','mirror','glass'],['silence','sanctuary','duel'],['velocity','mirror','silence'],['mercy','duel','sanctuary'],['glass','mirror','velocity'],['silence','mirror','duel']];
 const CLASSIC=[['mercy','mirror','glass'],['silence','sanctuary','duel'],['velocity','mirror','silence']];
 function context(input={}){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['mode','stage'].includes(k)))throw Error('Invalid campaign context');if(!MODES.includes(input.mode)||!Number.isInteger(input.stage)||input.stage<0||input.stage>5||(input.mode==='classic'&&input.stage>2))throw Error('Invalid campaign context');return {mode:input.mode,stage:input.stage};}
 function offers(input){const c=context(input),table=c.mode==='classic'?CLASSIC:EXPANSION,ids=table[c.stage];if(!ids)throw Error('No authored offers');return ids.map(id=>C.CONTRACTS.find(x=>x.id===id)).filter(Boolean).map(x=>({...x}));}
 function cleanRequest(request,ctx){const c=context(ctx);if(!request||typeof request!=='object'||Array.isArray(request)||request.task!=='negotiate'||request.stage!==c.stage)throw Error('Invalid request');const expected=offers(c).map(x=>x.id);if(!Array.isArray(request.allowed)||request.allowed.length!==expected.length||request.allowed.some((x,i)=>x!==expected[i]))throw Error('Offer list mismatch');const clean=I.cleanRequest(request);if(clean.task!=='negotiate'||clean.stage!==c.stage||clean.allowed.some((x,i)=>x!==expected[i]))throw Error('Offer list mismatch');return clean;}
 function describe(contractId,ctx){const c=context(ctx),found=offers(c).find(x=>x.id===contractId);if(!found)throw Error('Offer is not available');return {id:found.id,name:found.name,gift:found.gift,cost:found.cost,tip:found.tip};}
 function commentary(result,ctx){if(!result||typeof result!=='object')return null;const c=context(ctx);if(!['openai','local-rules'].includes(result.provider))return null;const decision=result.decision||result;let pact=result.campaignPact;try{const id=decision?.contractId||pact?.id;if(typeof id!=='string')return null;pact=describe(id,c);if(decision?.contractId!==id&&result.campaignPact?.id!==id)return null;}catch{return null;}return JSON.stringify({status:'unsigned',provider:result.provider,campaignPact:pact,instruction:'Review the canonical offer and click Sign to apply it.'});}
 const rival=ctx=>X.SECTORS[context(ctx).stage].boss.name;
 return {MODES,context,offers,cleanRequest,describe,commentary,rival};
});
