/* Explicit local demo recorder. Capture starts only after ?demo=1 and a click. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.NemesisDemo=factory();})(globalThis,function(){'use strict';
 const MAX_MS=60000;
 class DemoRecorder{
  constructor(o={}){this.document=o.document||globalThis.document;this.navigator=o.navigator||globalThis.navigator;this.MediaRecorder=o.MediaRecorder||globalThis.MediaRecorder;this.AudioContext=o.AudioContext||globalThis.AudioContext||globalThis.webkitAudioContext;this.MediaStream=o.MediaStream||globalThis.MediaStream;this.setTimeout=o.setTimeout||setTimeout;this.clearTimeout=o.clearTimeout||clearTimeout;this.setInterval=o.setInterval||setInterval;this.clearInterval=o.clearInterval||clearInterval;this.URL=o.URL||globalThis.URL;this.onState=o.onState||(()=>{});this.onDownload=o.onDownload||(()=>{});this.state='idle';this.button=null;this.help=null;this.display=null;this.recordStream=null;this.recorder=null;this.audioContext=null;this.destination=null;this.timer=null;this.countdown=null;this.generation=0;this.startedAt=0;this.remainingMs=0;this.voice={input:null,output:null};this._boundPagehide=()=>{this.generation++;this.stop('pagehide');};this._boundEnded=()=>this.stop('share-ended');}
  static enabled(search){return new URLSearchParams(search||globalThis.location?.search||'').get('demo')==='1';}
  attachVoice(stream,kind='input'){if(!stream?.getAudioTracks?.().length||!['input','output'].includes(kind))return false;this.voice[kind]=stream;if(this.state==='recording')this._connectVoice(kind);return true;}
  attach(){if(!this.document||!DemoRecorder.enabled())return false;if(this.button)return true;this.button=this.document.createElement('button');this.button.id='demo-record';this.button.type='button';this.button.className='demo-record';this.button.textContent='Record 60s demo';this.help=this.document.createElement('small');this.help.id='demo-record-help';this.help.textContent='Record this game tab and your voice locally. Nothing is uploaded.';this.button.addEventListener('click',()=>this.state==='recording'?this.stop('user'):this.start());this.document.body.append(this.button,this.help);this.document.defaultView?.addEventListener?.('pagehide',this._boundPagehide);return true;}
  _state(s,d=''){this.state=s;this.onState({state:s,detail:d,remainingMs:this.remainingMs});if(this.button){this.button.disabled=s==='starting';this.button.textContent=s==='recording'?`Stop recording (${Math.ceil(this.remainingMs/1000)}s)`:'Record 60s demo';}if(this.help&&s==='starting')this.help.textContent='Choose this game tab in the share dialog. Capture stays local; nothing is uploaded.';}
  _buildAudio(gen){if(!this.AudioContext||!this.MediaStream)return null;this.audioContext=new this.AudioContext();this.destination=this.audioContext.createMediaStreamDestination();const connect=stream=>{if(!stream?.getAudioTracks?.().length)return;const src=this.audioContext.createMediaStreamSource(stream);src.connect(this.destination);(this.sources??=[]).push(src);};this.hasTabAudio=this.display.getAudioTracks().length>0;this.voiceSources={};connect(this.display);this._connectVoice('input');this._connectVoice('output');if(gen!==this.generation)throw Error('stale-capture');return this.destination.stream.getAudioTracks()[0]||null;}
  _connectVoice(kind){if(!this.audioContext||!this.destination||kind==='output'&&this.hasTabAudio)return;const stream=this.voice[kind];if(!stream?.getAudioTracks().some(t=>t.readyState!=='ended'))return;this.voiceSources??={};this.voiceSources[kind]?.disconnect?.();const source=this.audioContext.createMediaStreamSource(stream);source.connect(this.destination);this.voiceSources[kind]=source;}
  async start(){if(this.state==='starting'||this.state==='recording')return false;if(!this.navigator?.mediaDevices?.getDisplayMedia||!this.MediaRecorder)return this._state('error','capture-unavailable'),false;const gen=++this.generation;this._state('starting','local-only');let display;try{display=await this.navigator.mediaDevices.getDisplayMedia({video:{frameRate:30},audio:true,preferCurrentTab:true,selfBrowserSurface:'include'});if(gen!==this.generation){display.getTracks().forEach(t=>t.stop());return false;}this.display=display;display.getVideoTracks().forEach(t=>t.addEventListener?.('ended',this._boundEnded,{once:true}));const audioTrack=this._buildAudio(gen);await this.audioContext?.resume?.();const tracks=[...display.getVideoTracks()];if(audioTrack)tracks.push(audioTrack);this.recordStream=new this.MediaStream(tracks);const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(x=>this.MediaRecorder.isTypeSupported?.(x))||'';this.recorder=new this.MediaRecorder(this.recordStream,mime?{mimeType:mime}:{});const rec=this.recorder,chunks=[];rec.addEventListener('dataavailable',e=>{if(e.data?.size)chunks.push(e.data);});rec.addEventListener('stop',()=>{if(this.recorder!==rec)return;const blob=new Blob(chunks,{type:rec.mimeType||'video/webm'}),url=this.URL?.createObjectURL?.(blob);if(url){const a=this.document?.createElement?.('a');if(a){a.href=url;a.download='nemesis-pact-demo.webm';a.click();}this.onDownload({blob,url});this.setTimeout(()=>this.URL?.revokeObjectURL?.(url),0);}this._release('saved');});this.startedAt=Date.now();this.remainingMs=MAX_MS;this._state('recording');rec.start(250);this.timer=this.setTimeout(()=>this.stop('duration-limit'),MAX_MS);this.countdown=this.setInterval(()=>{this.remainingMs=Math.max(0,MAX_MS-(Date.now()-this.startedAt));this._state('recording');},1000);return true;}catch(e){if(display&&gen===this.generation)display.getTracks().forEach(t=>t.stop());this._release('cancelled');this._state('error',e?.name==='NotAllowedError'?'share-cancelled':'capture-failed');return false;}}
  stop(reason='user'){if(this.state==='idle'||this.state==='stopped'||this.state==='stopping')return false;this.generation++;this.clearTimeout(this.timer);this.timer=null;this.clearInterval(this.countdown);this.countdown=null;this.remainingMs=Math.max(0,MAX_MS-(Date.now()-this.startedAt));const rec=this.recorder;if(rec?.state==='recording'){this._state('stopping',reason);rec.stop();}else this._release(reason);return true;}
  _release(reason){this.clearTimeout(this.timer);this.timer=null;this.clearInterval(this.countdown);this.countdown=null;const tracks=new Set([...(this.display?.getTracks?.()||[]),...(this.recordStream?.getTracks?.()||[])]);tracks.forEach(t=>t.stop?.());this.display=null;this.recordStream=null;try{this.audioContext?.close?.();}catch{}this.audioContext=null;this.destination=null;this.sources=null;this.recorder=null;this._state(reason==='saved'?'stopped':'idle',reason);}
 }
 const singleton=new DemoRecorder();singleton.DemoRecorder=DemoRecorder;for(const k of ['attachVoice','attach','start','stop'])singleton[k]=singleton[k].bind(singleton);return singleton;
});
